### ISSUE TITLE
-I/--interactive does not work

### ISSUE THREAD

**Issue by seanaguinaga** [tobias-tengler/create-relay-app#14]
I want to enable subscriptions but -I/--interactive does not work

**Comment by seanaguinaga** [comment]
With npm create

yarn create works fine

**Comment by tobias-tengler** [comment]
"Does not work" means nothing happens or you get an error?
Could you provide some more information, like the type of project you're using and the output of the command?

**Comment by seanaguinaga** [comment]
A fresh TypeScript CRA Template - it ignores the --interactive flag and proceeds without stopping for input

**Comment by tobias-tengler** [comment]
Interesting. `npm create` requires you to pass `--` before specifying the command arguments:

```bash
npm create @tobiastengler/relay-app -- --interactive
```

I wasn't aware of this either. I'll update the documentation. Thanks for the find :)

**Comment by tobias-tengler** [comment]
I added a quick reminder [here](https://github.com/tobias-tengler/create-relay-app/blob/main/README.md#arguments).
