### ISSUE TITLE
NextJS: `Module not found: Can't resolve 'relay-runtime'`

### ISSUE THREAD

**Issue by satvikpendem** [tobias-tengler/create-relay-app#15]
Seems like `relay-runtime` isn't added in the package list, causing `npm run dev` or `yarn dev` to fail. When I manually added `relay-runtime` NextJS says everything compiled successfully.

**Comment by tobias-tengler** [comment]
Hi, thanks for reporting this :)

I just published `v2.1.1` which addresses this, by also installing the `relay-runtime` package.
