### ISSUE TITLE
Friendlier error message on missing package.json

### ISSUE THREAD

**Issue by damassi** [tobias-tengler/create-relay-app#2]
Just saw your comment [here](https://github.com/facebook/relay/issues/3815#issuecomment-1214227347) and wanted to take for a spin! I too agree that Relay has some onboarding issues. 

One issue I just encountered was after running ` npx @tobiastengler/create-relay-app` and then getting the error `Error: package.json file is missing`. I initially thought that this would bootstrap whatever framework the user chose before setting up the Relay bits (eg, `npx create-next-app`), so seeing that issue was a bit confusing. Maybe something like 

```
Error: package.json file is missing. Did you remember to setup <create-react-app|next|vite> before running this command?
```

Would fix the issue.

**Comment by tobias-tengler** [comment]
Thank you for the feedback, I'll incorporate it :)

**Comment by tobias-tengler** [comment]
The error message reads now as follows:

![image](https://user-images.githubusercontent.com/45513122/184530413-c234a1fa-3ae0-40fa-b108-93575c9df62f.png)

**Comment by damassi** [comment]
👌
