### ISSUE TITLE
Add Relay plugin configuration: Unexpected error

### ISSUE THREAD

**Issue by damassi** [tobias-tengler/create-relay-app#3]
After setting up next and running `npx @tobiastengler/create-relay-app` and selecting the `next` option, this output appears:

```sh
test [main] % npx @tobiastengler/create-relay-app
? Select the toolchain your project is using Next.js
? Select the language of your project Typescript
? Select the path to your GraphQL schema file ./src/schema.graphql
? Select the package manager you wish to use to install packages npm

✔ Add Relay dependencies: react-relay
✔ Add Relay devDependencies: relay-compiler @types/react-relay
✔ Add Relay configuration to package.json
✖ Add Relay plugin configuration   Unexpected error

### NEXT STEPS ###
1. Replace ./src/schema.graphql with your own GraphQL schema file.
2. Replace the HOST variable in the RelayEnvironment.ts file.
```

Not sure why the last step yields `Unexpected error`.

**Comment by tobias-tengler** [comment]
You need to run with the `@experimemtal` tag. Otherwise it chooses the first version I ever published. I'll soon publish a v1, so then it should no longer be an issue. Let me know if this resolves your issue. :)

**Comment by tobias-tengler** [comment]
I've also noticed another issue with next, when not using JavaScript. I'm looking into it :)

**Comment by tobias-tengler** [comment]
All issues with next should be resolved in the latest version. I'm publishing a v0.0.1 in a few minutes :)
